name: Building docker images to run challenge locally

on:
  push:
    paths:
      - 'Dockerfile'
  pull_request:
    paths:
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build for PHP
        run: docker build --target php . -t aurelijusbanelis/challenge:php
      - name: Build for JavaScript
        run: docker build --target js . -t aurelijusbanelis/challenge:js
      - name: Build for Go
        run: docker build --target go . -t aurelijusbanelis/challenge:go
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: aurelijuschallengebot
          password: ${{ secrets.DOCKERHUB_TOKEN_CHALLENGE_BOT }}
      - name: Pushing latest images
        run: |
          docker push aurelijusbanelis/challenge:php
          docker push aurelijusbanelis/challenge:js
          docker push aurelijusbanelis/challenge:go
